name: BankNotes
main: AndreasHGK\BankNotes\Main
version: 1.0.0
api: [3.0.0-ALPHA12, 3.0.0, 4.0.0, 4.0.0-ALPHA1]
load: POSTWORLD
author: AndreasHGK
description: A plugin that makes money into an item to trade with!
softdepend: ["EconomyAPI"]

commands:
 withdraw:
  description: "Withdraw money and put it on a bank note"
  usage: "/withdraw {amount}"
  permission: banknotes.get
 bn:
  description: "Withdraw money and put it on a bank note"
  usage: "/bn {amount}"
  permission: banknotes.get
 bns:
  description: "Withdraw money and put it on a bank note"
  usage: "/bns {amount}"
  permission: banknotes.get
 deposit:
  description: "Deposit a note to your account"
  usage: "/deposit"
  permission: banknotes.deposit

permissions:
 banknotes:
  default: true
  description: "bankNotes root permission (useless)"
  children:
   banknotes.get:
    default: true
    description: "allow players to withdraw banknotes"
   banknotes.deposit:
    default: true
    description: "allow players to deposit banknotes"
